# Generated by Django 2.0.5 on 2018-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attach',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
