# Generated by Django 2.0.5 on 2018-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
