# Generated by Django 2.0.5 on 2018-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attach',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargoDescripton',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
