# Generated by Django 2.0.5 on 2018-06-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180603_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='attach',
            new_name='attach1',
        ),
        migrations.AddField(
            model_name='order',
            name='attach2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='attach3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='attach4',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
