# Generated by Django 2.0.5 on 2018-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180603_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='attach1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='attach2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='attach3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='attach4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
