# Generated by Django 2.0.5 on 2018-06-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180614_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='outputOrg',
            field=models.CharField(max_length=1000),
        ),
    ]
